# Generated by Django 5.0.4 on 2024-05-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
