# Generated by Django 5.0.4 on 2024-05-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0003_remove_product_is_sale_remove_product_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='uploads/category/'),
        ),
    ]
