# Generated by Django 5.0.4 on 2024-06-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0006_alter_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address1',
            new_name='Lastame',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
    ]
