# Generated by Django 5.0.4 on 2024-06-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazonapp', '0007_rename_phone_profile_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_date',
        ),
    ]
